
POST http://localhost:8080/api/users
Content-Type: application/json

{
	"email": "test@email.co"
}

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
	"email": "test2@email.co"
}

###

POST http://localhost:8080/admin/reset


###

GET http://localhost:8080/api/chirps?author_id=b4136f97-2f35-415d-ae81-e4def7a3a711